style: "angular"

template: CHANGELOG.tpl.md

info:
  title: "Changelog"
  repository_url: "https://github.com/yourusername/yourrepository"

options:
  commits:
    filters:
      Type:
        - feat
        - fix
        - perf
  commit_groups:
    title_maps:
      feat: "Features"
      fix: "Bug Fixes"
      perf: "Performance Improvements"
  header:
    pattern: "^(\\w*)\\: (.*)$"
    pattern_maps:
      - Type
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE

template-variables:
  Commit: "{{.Hash.Short}} - {{.Subject}}"
