name: Java CI

on:
  push:
    branches: [ lab8 ]
  pull_request:
    branches: [ lab8 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'adopt'
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Test with Maven
      run: mvn test
