name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 19
      uses: actions/setup-java@v2
      with:
        java-version: '19'
        distribution: 'temurin' # Adding the correct distribution here


    #  steps to build project and run tests here
    - name: Build and Test
      run: |
        mvn package
        mvn test

    #to create a jar of my application
    - name: Build with Maven
      run: mvn package


    # This step will only execute if the build and test steps are successful
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: release-${{ github.run_id }}
        release_name: Release-${{ github.run_id }}
        draft: false
        prerelease: false



